python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_600/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_600_hf
python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_500/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_500_hf
python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_400/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_400_hf
python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_300/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_300_hf
python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_200/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_200_hf
python3 -m verl.model_merger merge     --backend fsdp     --local_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_100/actor/     --target_dir /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_100_hf


CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_600_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_600_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_500_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_500_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_400_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_400_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_300_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_300_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_300_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_300
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_200_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_200_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_200_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_200
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_100_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_100_t0 --temperature 0
CUDA_VISIBLE_DEVICES=5 python inference_vllm_ids_export.py --model_path /mnt/local2/wxy/herb_rec+RLv2/verl/checkpoints/verl_grpo_tcm_rerank/qwen3_4b_tcm_focus5_c30_rewardv19_sft/global_step_100_hf  --test_parquet /mnt/local2/wxy/herb_rec+RLv2/data/tcm_herb_rerank_c30_full_v10/test.parquet --tag qwen3_4b_sft4_v19_100
